version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: ms-user-container
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ms-user
    volumes:
      - ms-user_pg_data:/bitnami/postgresql
    networks:
      - ms-user-email-network

volumes:
  ms-user_pg_data:
networks:
  ms-user-email-network:
    external: true